Migrated to twig (Fork CMS 4.x)
ikoene/fork-cms-module-slideshow pull request #9
Opened 2016-08-11 13:17 UTC by wouterverstuyf

Hello @ikoene 

Ik heb de slideshow module gemigreerd naar Twig, zodat deze compatibel is met de laatste versie van Fork CMS.

Test gerust even uit en laat eventuele feedback maar horen!

Thx.

Groeten
Wouter
www.webflow.be

2016-08-11 15:15 UTC, WouterSchoofs commented
+1

2016-08-19 07:13 UTC, ikoene commented on src/Frontend/Modules/Slideshow/Layout/Templates/Category.html.twig
> -        {{ galleri.publish_on|spoon_date(dateFormatLong,LANGUAGE ) }}
Typo (`gallery`)

2016-08-19 07:14 UTC, ikoene commented on src/Frontend/Modules/Slideshow/Layout/Templates/Detail.html.twig
> +              <li data-thumb="/src/Frontend/Files/slideshow/thumbnails/{{ _itr_0.filename }}">
What's up with this var naming? `_itr_0.filename` 

Shouldn't it be something like `{{ slideshow.filename }}`

2016-08-19 07:15 UTC, ikoene commented on src/Frontend/Modules/Slideshow/Layout/Templates/Detail.html.twig
> +                  <img src="/src/Frontend/Files/slideshow/{{ _itr_0.filename }}" alt="{{ _itr_0.title }}" />
Same here.

2016-08-23 20:22 UTC, ikoene commented
The category name is not parsed in the **confirmation message** when deleting a category.

<img width="596" alt="schermafbeelding 2016-08-23 om 22 20 08" src="https://cloud.githubusercontent.com/assets/1136847/17908236/e1c44dfe-697f-11e6-9e49-9a9a9b3d0179.png">

2016-08-23 20:31 UTC, ikoene commented
Small styling issue on EditImage action.

<img width="702" alt="schermafbeelding 2016-08-23 om 22 30 18" src="https://cloud.githubusercontent.com/assets/1136847/17908576/4a3b7e74-6981-11e6-9dc3-5b6377932224.png">

2016-08-23 20:35 UTC, ikoene commented
When clicking on the **amount of images** to on the slideshow overview, you should be redirected to the images tab on the slideshow detail, which isn't the case. Probably has something to do with the url.

<img width="1130" alt="schermafbeelding 2016-08-23 om 22 32 55" src="https://cloud.githubusercontent.com/assets/1136847/17908665/b34d5022-6981-11e6-8cf0-737ae0c6341b.png">

<img width="537" alt="schermafbeelding 2016-08-23 om 22 33 28" src="https://cloud.githubusercontent.com/assets/1136847/17908670/b80964fc-6981-11e6-9530-eef42651d6fd.png">

2016-08-23 20:50 UTC, ikoene commented
The internal/external link logic from the old build is not present here. The **external link textfield** should only be visible when the **external link checkbox** is checked.

Furthermore, the external link textfield should only be validated when the external link checkbox is checked.

I've included a gif which demonstrates the correct behaviour.

<img width="477" alt="schermafbeelding 2016-08-23 om 22 41 35" src="https://cloud.githubusercontent.com/assets/1136847/17909051/174cce58-6983-11e6-94c0-e2ce607e25ec.png">

![5c29fd7d58cde9ae8be10970aac03614](https://cloud.githubusercontent.com/assets/1136847/17909056/1ad39548-6983-11e6-926d-9100c60cf343.gif)

2016-08-23 20:57 UTC, ikoene commented
The **Settings** tab should not be visible when you've opted *not* to have **settings per slideshow**.

<img width="461" alt="schermafbeelding 2016-08-23 om 22 56 53" src="https://cloud.githubusercontent.com/assets/1136847/17909485/ef3015d6-6984-11e6-912b-56cf220f5539.png">


<img width="994" alt="schermafbeelding 2016-08-23 om 22 54 05" src="https://cloud.githubusercontent.com/assets/1136847/17909391/96dd2d6a-6984-11e6-9b83-2ab5a6e4d4a8.png">

2016-08-23 21:04 UTC, ikoene commented
There are several styling issues with a rendered slideshow in the frontend. See screenshot for more details.

<img width="717" alt="schermafbeelding 2016-08-23 om 23 02 24" src="https://cloud.githubusercontent.com/assets/1136847/17909687/dc3da0c8-6985-11e6-916c-0d27303b1436.png">

2016-08-23 21:10 UTC, ikoene commented
You should *not* be able to deleted a category that's used for a slideshow. 

Currently, you can do this. Not only is the category deleted, but the slideshows using the category are not visible in the overview.

<img width="798" alt="schermafbeelding 2016-08-23 om 23 07 26" src="https://cloud.githubusercontent.com/assets/1136847/17909808/71c8d8f6-6986-11e6-918e-ca75c9fbac8c.png">

2016-08-23 21:13 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Add.html.twig
> +                        {% for _itr_4 in hidden %}
Not sure what this `_itr_4` naming thing is, but you should replace it by something more meaningful.

2016-08-23 21:14 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Edit.html.twig
> +                        {% for _itr_4 in hidden %}
Same here.

2016-08-23 21:14 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/EditImage.html.twig
> +                        {% for _itr_4 in hidden %}
Same here.

2016-08-23 21:20 UTC, ikoene commented
A slideshow title is required, but the title label is missing an asterisk (*).

<img width="507" alt="schermafbeelding 2016-08-23 om 23 19 10" src="https://cloud.githubusercontent.com/assets/1136847/17910188/1a84d336-6988-11e6-8251-466d3ec67349.png">

2016-08-23 21:29 UTC, ikoene commented
All in all good effort, but it needs some polish 😉

2016-08-24 06:26 UTC, wouterverstuyf commented
@ikoene Thx, it's the polish that makes something really good ;)
I will take a look at it the following weeks, at the moment a bit busy, if someone wants to help you're welcome!

2016-08-24 16:17 UTC, ikoene commented
Several `.DS_Store` files commited.

2016-08-27 21:41 UTC, ikoene commented
Allright, making good progress 👍 

I don't know if it's just me, but the slideshow animation seems to be absent. It doesn't seem to **slide** or **fade**. I noticed that the animation is present twice (`animation` & `animation_type`) in the JS. Could that be the cause?

<img width="1604" alt="schermafbeelding 2016-08-27 om 23 36 34" src="https://cloud.githubusercontent.com/assets/1136847/18030252/8d6fa3ba-6caf-11e6-9c05-f8042137e452.png">

2016-08-27 21:50 UTC, ikoene commented
Also, there's something wrong with the `max-width` for a slideshow (maybe it's related to the previous issue). The max-width is not taken into account.

<img width="384" alt="schermafbeelding 2016-08-27 om 23 48 11" src="https://cloud.githubusercontent.com/assets/1136847/18030291/dc635e84-6cb0-11e6-9fa7-0ad835798a5e.png">

2016-08-27 21:53 UTC, ikoene commented
The code in the `Add` action (src/Backend/Modules/Slideshow/Actions/Add.php) seems to be entirely new if I check the diff (see **Files changed** tab). I'm not sure how this is possible since there are only small tweaks to the file...

2016-08-27 21:56 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Add.html.twig
> +                        <label for="height" class="control-label">{{ 'lbl.Width'|trans|capitalize }}<abbr title="{{ 'lbl.RequiredField'|trans }}">*</abbr></label>
Should be `for="width"`.

2016-08-27 21:59 UTC, ikoene commented on src/Frontend/Modules/Slideshow/Layout/Widgets/Slideshow.html.twig
> +      <div class="flex-container" id="flex{{ widgetGallery.id }}" style="max-width:widgetGallery.widthpx">
Brackets are missing around `widgetGallery.width`.

2016-08-27 22:00 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Add.html.twig
> +  <div class="row fork-module-content">
From here on the indentation is not correct.

2016-08-27 22:02 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Edit.html.twig
> +                        <label for="height" class="control-label">{{ 'lbl.Width'|trans|capitalize }}<abbr title="{{ 'lbl.RequiredField'|trans }}">*</abbr></label>
Should be `for="width"`.

2016-08-27 22:05 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/EditCategory.html.twig
> +      {% if showSlideshowDeleteCategory %}
This should probably be `{% if deleteCategoryAllowed %}`.

2016-08-27 22:06 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/EditImage.html.twig
> +          <a href="{{ geturl('DeleteImage' ) }}&amp;id={{ item.id }}&amp;gallery_id={{ item.gallery_id }}" class="btn btn-danger">
Superflous space after 'DeleteImage'.

`{{ geturl('DeleteImage') }}`

2016-08-27 22:07 UTC, ikoene commented on src/Backend/Modules/Slideshow/Layout/Templates/Edit.html.twig
> +                <a href="{{ geturl('add_image' ) }}&amp;id={{ item.id }}" class="btn btn-primary">
Superfluous space after `add_image`.

`geturl('add_image')`

2016-08-27 22:09 UTC, ikoene commented on src/Frontend/Modules/Slideshow/Layout/Templates/Category.html.twig
> +        {{ gallery.publish_on|spoondate(dateFormatLong,LANGUAGE ) }}
Superfluous space after `LANGUAGE`.

`spoondate(dateFormatLong,LANGUAGE)`

2016-09-14 18:20 UTC, ikoene requested changes
Hey @wouterverstuyf Checking out this new review feature in GitHub to check on your progress :) How's it going? Need any help?

2016-09-15 10:05 UTC, wouterverstuyf commented
Hi @ikoene, It's still on the to do list, but I'm full with some projects at the moment. I try to find time soon... Of course, any help can speed up the progress :)

2016-10-03 21:15 UTC, ikoene commented
Good job 👍 Did some testing, works great!

2016-10-03 21:16 UTC, ikoene approved these changes

2016-10-03 21:16 UTC, merged